### ISSUE TITLE
[meta ticket] cross domain fixes

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#376]
@mehak-sachdeva, mark each of these complete once they pass ticket #375 on all counts

Fix cross-domain issue for 'live/working maps':

- [x] [createVis vs createLayer](https://carto.com/academy/courses/cartojs-ground-up/createvis-vs-createlayer/)
- [x] [Creating basic map app](https://carto.com/academy/courses/cartojs-ground-up/creating-basic-map-apps/)
- [x] [Basic interactivity](https://carto.com/academy/courses/cartojs-ground-up/basic-interactivity/)
- [x] [Torque.js](https://carto.com/academy/courses/cartojs-ground-up/torquejs/)
- [x] [Named maps](https://carto.com/academy/courses/cartojs-ground-up/named-maps/)

Additionally, to avoid this issue in the future:

- [x] Create guidelines separating examples:
    * Example code (e.g., https://raw.githubusercontent.com/CartoDB/academy/master/_app/t/03-cartodbjs-ground-up/lesson-4/bonus.html)
    * Code templates (e.g., https://raw.githubusercontent.com/CartoDB/academy/master/_app/t/03-cartodbjs-ground-up/lesson-4/template.html)
    * Live (hosted) versions (e.g., `{{ site.baseurl }}/academy/t/03-cartodbjs-ground-up/lesson-5/named-maps-example-hosted.html`)
- [x] Decide on naming conventions
- [x] Decide on where they are linked from (GitHub raw, right click to download, GitHub codeview page [maybe to encourage open source participation], etc. etc.)
- [x] Write down these guidelines in the 'Map Academy Guide Document'

**Comment by ohasselblad** [comment]
Nice work!
